[workspace]
members = ["pi_to_nth_digit", "e_to_nth_digit", "fibonacci_sequence", "prime_factorization", "next_prime_number", "w_h_floor", "mortgage", "change_return", "bin_to_dec", "calculator", "unit_converter"]

